name: pull-request

on: pull_request

jobs:
  print-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Print github.event
        uses: actions/github-script@v7
        with:
          script: console.log(JSON.stringify(github, null, 2));
